// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RapidProject.ConsoleApp.Models;

public partial class Invoice
{
    public string InvoiceId { get; set; }

    public int RentalId { get; set; }

    public decimal? Amount { get; set; }

    public DateTime? InvoiceDate { get; set; }

    public virtual Payment InvoiceNavigation { get; set; }

    public virtual Rental Rental { get; set; }
}