// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RapidProject.ConsoleApp.Models;

[Table("VehicleType")]
public partial class VehicleType
{
    [Key]
    public int VehicleTypeId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string VehicleTypeName { get; set; }

    // Properti Koleksi Navigasi
    public ICollection<Vehicle> Vehicles { get; set; }
}