// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RapidProject.VehicleRentMvc.Models;

[PrimaryKey("PaymentId", "InvoiceId")]
public partial class Payment
{
    [Key]
    public int PaymentId { get; set; }

    [Key]
    [StringLength(25)]
    [Unicode(false)]
    public string InvoiceId { get; set; }

    [Column(TypeName = "money")]
    public decimal? Amount { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? InvoiceDate { get; set; }
}