// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RapidProject.VehicleRentMvc.Models;

public partial class Rental
{
    [Key]
    public int RentalId { get; set; }

    public int UserId { get; set; }

    public int VehicleId { get; set; }

    public DateTime RentalDate { get; set; }

    public DateTime ReturnDate { get; set; }

    public byte Status { get; set; }

    public Vehicle Vehicle { get; set; }
    public User User { get; set; }
}