// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RapidProject.VehicleRentMvc.Models;

public partial class User
{
    [Key]
    public int UserId { get; set; }

    [Required]
    [StringLength(25)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required]
    [StringLength(25)]
    [Unicode(false)]
    public string Password { get; set; }

    public byte Role { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string FullName { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string PhoneNumber { get; set; }
}