// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RapidProject.VehicleRentMvc.Models;

[Table("VehicleImage")]
public partial class VehicleImage
{
    [Key]
    public int VehicleId { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string ImageURL { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string ImageName { get; set; }

    [InverseProperty("VehicleNavigation")]
    public virtual Vehicle Vehicle { get; set; }
}