// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RapidProject.VehicleRentMvc.Models;

public partial class VehicleType
{
    [Key]
    public int VehicleTypeId { get; set; }

    [Required]
    [Column("VehicleType")]
    [StringLength(10)]
    [Unicode(false)]
    public string VehicleType1 { get; set; }

    [InverseProperty("VehicleType")]
    public virtual ICollection<Vehicle> Vehicles { get; set; } = new List<Vehicle>();
}