// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RapidProject.VehicleRentMvc.Models;

public partial class Vehicle
{
    [Key]
    public int VehicleId { get; set; }

    public int VehicleTypeId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Make { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Model { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Year { get; set; }

    [Column(TypeName = "money")]
    public decimal RentalPrice { get; set; }

    public int AvailabilityStatus { get; set; }

    [InverseProperty("Vehicle")]
    public virtual ICollection<Rental> Rentals { get; set; } = new List<Rental>();

    [ForeignKey("VehicleId")]
    [InverseProperty("Vehicle")]
    public virtual VehicleImage VehicleNavigation { get; set; }

    [ForeignKey("VehicleTypeId")]
    [InverseProperty("Vehicles")]
    public virtual VehicleType VehicleType { get; set; }
}